
steps:
  # Checkout source code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Kavipraveen/simple-webapp.git']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/usecase-4-ci-cd/usecase4cicd/webapp:latest', '.']
 
  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/usecase-4-ci-cd/usecase4cicd/webapp:latest']
