
steps:
  # Checkout source code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Kavipraveen/simple-webapp.git']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/usecase-4-ci-cd/usecase4cicd/webapp:latest', '.']
 
  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/usecase-4-ci-cd/usecase4cicd/webapp:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'webapp-deploy', '--image', 'us-central1-docker.pkg.dev/usecase-4-ci-cd/usecase4cicd/webapp:latest', '--region', 'us-central1']
    images:
      - us-central1-docker.pkg.dev/usecase-4-ci-cd/usecase4cicd/webapp:latest
