# Define variables for project ID, image name, and tag.
# Customize these values as needed.
substitutions:
  _PROJECT_ID: 'usecase4-ci-cd'  # Replace with your actual project ID.
  _IMAGE_NAME: 'gcr.io/usecase4-ci-cd/usecase4cicd'
  _TAG_NAME: 'latest'
  _REGION: 'us-central1'  # Replace with your preferred region.
  _SERVICE_NAME: 'usecase4cicd'  # Replace with your preferred Cloud Run service name.


steps:
  # Checkout source code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Kavipraveen/simple-webapp.git']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/usecase4-ci-cd/usecase4cicd', '.']
 
  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/usecase4-ci-cd/usecase4cicd']


    # Deploy to Cloud Run.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_IMAGE_NAME}:${_TAG_NAME}'
  - '--platform=managed'
  - '--region=${_REGION}'
  - '--allow-unauthenticated'  # Optional: Remove this line if you don't want to allow unauthenticated access.

images:
- '${_IMAGE_NAME}:${_TAG_NAME}'  # Reference the dynamic image name and tag.
